In [2]:
import numpy as np

In [22]:
rng = np.random.default_rng(seed=42)

In [27]:
data = rng.random((200, 4))

In [28]:
print(data)

[[9.13285184e-01 1.40055405e-01 6.77708614e-01 8.14473876e-01]
 [2.35256388e-01 2.76207363e-01 9.64518886e-01 2.64597605e-01]
 [4.29957050e-01 4.32515593e-01 2.53034750e-01 7.75791086e-01]
 [7.71849343e-01 3.78318014e-01 8.35125791e-01 2.13074934e-01]
 [4.30577567e-03 5.71167362e-01 9.94077772e-01 3.86443098e-02]
 [2.07998074e-01 5.18914642e-01 8.09940736e-01 8.90420051e-02]
 [3.95234654e-01 7.47075801e-01 3.71543208e-01 1.88836420e-01]
 [1.95495827e-01 4.10048787e-01 4.79417075e-01 8.61814418e-01]
 [6.42252419e-01 6.90401955e-01 9.82987172e-01 4.11843440e-01]
 [4.03354403e-01 9.23346968e-01 2.45875587e-01 7.29815246e-01]
 [7.54573138e-01 9.77879974e-02 4.68231406e-01 2.00562471e-01]
 [1.85375273e-01 4.63828110e-01 2.89429708e-01 7.96060448e-01]
 [9.07604891e-01 8.02720605e-01 2.66030873e-01 2.74134394e-01]
 [2.54728350e-01 1.35038096e-01 9.43798368e-01 4.02047798e-01]
 [2.24689475e-01 8.46671051e-01 3.99195303e-01 3.51168111e-02]
 [1.61941570e-01 6.39250340e-01 7.82905274e-01 2.109343