## Synthetic laboratory data

This notebook uses NumPy to generate a synthetic dataset of 200 samples with four laboratory measurements: hemoglobin, glucose, creatinine, and CRP.

A fixed random seed of 42 is used to make the results reproducible.

| Hemoglobin | g/L |  
| Glucose | mg/dL |  
| Creatinine | mg/dL |  
| CRP | mg/L |  

The measurements are generated from normal distributions using synthetic means and standard deviations. These values are illustrative and do not reflect real-life values.

In [17]:
import numpy as np

In [18]:
rng = np.random.default_rng(seed=42)

In [24]:
hemoglobin = rng.normal(
    loc = 145,
    scale=12.5,
    size=200
)
glucose = rng.normal(
    loc = 85,
    scale=7.5,
    size=200
)
creatinine = rng.normal(
    loc = 0.9,
    scale=0.2,
    size=200
)
crp = rng.normal(
    loc = 0.8,
    scale=0.2,
    size=200
)

In [39]:
data = np.stack((hemoglobin, glucose, creatinine, crp), axis=-1)
column_names = ["hemoglobin", "glucose", "creatinine", "CRP"]
units = ["g/L", "mg/dL", "mg/dL", "mg/L"]

In [40]:
print(data.shape)
print(data.dtype)
print(data[:5])

(200, 4)
float64
[[166.61244176  82.87903188   0.6701592    0.49704904]
 [161.9902575   84.20363552   0.51837392   0.96582421]
 [148.19016771  86.67341514   0.87662396   0.88097102]
 [161.88281401  89.6261065    0.7004296    0.47894575]
 [145.15066476  77.50215828   0.88302989   0.79514052]]


In [68]:
upper_limits = np.array([190, 105, 1.3, 1.1])
lower_limits = np.array([100, 75, 0.45, 0.2])

In [62]:
means = data.mean(axis=0)
stds = data.std(axis=0)

In [63]:
print(means, means.shape)
print(stds, stds.shape)

[144.62193542  85.33419063   0.89180283   0.78628207] (4,)
[12.68197613  7.02296705  0.21014802  0.21135043] (4,)


In [64]:
standardized = (data - means) / stds

In [65]:
standardized.shape

(200, 4)

In [66]:
standardized[:5]

array([[ 1.73399682, -0.34958996, -1.05470244, -1.36849986],
       [ 1.36952805, -0.1609797 , -1.7769804 ,  0.84949979],
       [ 0.28136248,  0.19069213, -0.0722294 ,  0.44801871],
       [ 1.36105591,  0.61112573, -0.91065919, -1.4541552 ],
       [ 0.0416914 , -1.11520277, -0.04174645,  0.04191357]])

In [67]:
print(standardized.mean(axis=0))
print(standardized.std(axis=0))

[-1.60794988e-15 -3.55410146e-15  2.64233080e-16  7.48290319e-16]
[1. 1. 1. 1.]


In [69]:
below_range = data < lower_limits
above_range = data > upper_limits

In [70]:
print(below_range.shape)
print(above_range.shape)

(200, 4)
(200, 4)


In [76]:
abnormal = below_range | above_range
abnormal_counts = abnormal.sum(axis=1)

In [78]:
print(abnormal_counts)

[0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0
 0 1 0 0 1 0 1 1 0 1 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 1 1 0 0 0 0 0 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 1 0 1 0
 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 2 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 1 1 0 1 1 0 0 1 0 0 0 1 0 0 0 0 0
 0 0 0 1 1 0 0 0 1 0 0 0 0 0 0]


In [83]:
standardized_loop = []
for row in data:
    new_row =[]
    for i, col in enumerate(row):
        new_row.append((col - means[i]) / stds[i])
    standardized_loop.append(new_row)


In [84]:
standardized_loop = np.array(standardized_loop)

In [85]:
print(standardized_loop[:5])

[[ 1.73399682 -0.34958996 -1.05470244 -1.36849986]
 [ 1.36952805 -0.1609797  -1.7769804   0.84949979]
 [ 0.28136248  0.19069213 -0.0722294   0.44801871]
 [ 1.36105591  0.61112573 -0.91065919 -1.4541552 ]
 [ 0.0416914  -1.11520277 -0.04174645  0.04191357]]


In [86]:
print(standardized[:5])

[[ 1.73399682 -0.34958996 -1.05470244 -1.36849986]
 [ 1.36952805 -0.1609797  -1.7769804   0.84949979]
 [ 0.28136248  0.19069213 -0.0722294   0.44801871]
 [ 1.36105591  0.61112573 -0.91065919 -1.4541552 ]
 [ 0.0416914  -1.11520277 -0.04174645  0.04191357]]


In [88]:
print((standardized == standardized_loop).sum())

800
